import { db } from './db'
import type { WeekTarget, DSAProblem, Resource, Skill, Tactic, PrepEntry } from './types'

// ── Week Targets (39 weeks) ───────────────────────────────────────────────────
export const WEEK_TARGETS_SEED: Omit<WeekTarget, 'id'>[] = [
  // Phase 1
  { phase: 'Phase 1', week: 'Wk 1',  weekNumber: 1,  lcTarget: 10,  mockInterviews: 0, githubProjects: 0, deliverable: 'Resume updated on Naukri + LinkedIn. Headline + ATS keywords fixed. Sign up Instahyre, Hirist, Cutshort, Wellfound, Peerlist', status: 'Not Started' },
  { phase: 'Phase 1', week: 'Wk 2',  weekNumber: 2,  lcTarget: 22,  mockInterviews: 0, githubProjects: 0, deliverable: '5 job applications + 15 LinkedIn DMs. Sign up Grapevine. Join r/developersIndia Discord', status: 'Not Started' },
  { phase: 'Phase 1', week: 'Wk 3',  weekNumber: 3,  lcTarget: 36,  mockInterviews: 0, githubProjects: 0, deliverable: '10 more applications + NIT Trichy alumni outreach (20 DMs)', status: 'Not Started' },
  { phase: 'Phase 1', week: 'Wk 4',  weekNumber: 4,  lcTarget: 50,  mockInterviews: 1, githubProjects: 0, deliverable: '1st Pramp mock interview. Book 1 Topmate session at target company', status: 'Not Started' },
  { phase: 'Phase 1', week: 'Wk 5',  weekNumber: 5,  lcTarget: 65,  mockInterviews: 0, githubProjects: 0, deliverable: 'NestJS Todo API with JWT on GitHub. Start Docker basics (Dockerfile + docker-compose)', status: 'Not Started' },
  { phase: 'Phase 1', week: 'Wk 6',  weekNumber: 6,  lcTarget: 80,  mockInterviews: 0, githubProjects: 0, deliverable: 'Docker-compose all projects. Redis cache-aside pattern added to NestJS project', status: 'Not Started' },
  { phase: 'Phase 1', week: 'Wk 7',  weekNumber: 7,  lcTarget: 95,  mockInterviews: 0, githubProjects: 0, deliverable: 'Kafka demo: NestJS producer + consumer with docker-compose. Add to GitHub', status: 'Not Started' },
  { phase: 'Phase 1', week: 'Wk 8',  weekNumber: 8,  lcTarget: 110, mockInterviews: 2, githubProjects: 1, deliverable: 'Full-stack Next.js 15 + NestJS app live on Vercel + Railway with README + live URL', status: 'Not Started' },
  // Phase 2
  { phase: 'Phase 2', week: 'Wk 9',  weekNumber: 9,  lcTarget: 120, mockInterviews: 0, githubProjects: 0, deliverable: 'GraphQL endpoint added to NestJS. Query + Mutation + basic resolver', status: 'Not Started' },
  { phase: 'Phase 2', week: 'Wk 10', weekNumber: 10, lcTarget: 130, mockInterviews: 0, githubProjects: 0, deliverable: 'Next.js 15 Server Actions + ISR mastered. Add Sentry error tracking to Next.js project', status: 'Not Started' },
  { phase: 'Phase 2', week: 'Wk 11', weekNumber: 11, lcTarget: 138, mockInterviews: 0, githubProjects: 0, deliverable: 'Playwright E2E: 8 tests covering login, dashboard, error states, accessibility', status: 'Not Started' },
  { phase: 'Phase 2', week: 'Wk 12', weekNumber: 12, lcTarget: 145, mockInterviews: 0, githubProjects: 0, deliverable: 'SQL deep practice: 25 LeetCode SQL medium-hard (window functions, CTEs, recursive)', status: 'Not Started' },
  { phase: 'Phase 2', week: 'Wk 13', weekNumber: 13, lcTarget: 150, mockInterviews: 3, githubProjects: 0, deliverable: '150 LC MILESTONE! Resume updated. Naukri refreshed. LinkedIn Open to Work enabled', status: 'Not Started' },
  // Phase 3
  { phase: 'Phase 3', week: 'Wk 14', weekNumber: 14, lcTarget: 156, mockInterviews: 0, githubProjects: 0, deliverable: 'HLD: URL shortener + rate limiter diagrams on Excalidraw. Post on LinkedIn', status: 'Not Started' },
  { phase: 'Phase 3', week: 'Wk 15', weekNumber: 15, lcTarget: 162, mockInterviews: 0, githubProjects: 0, deliverable: 'HLD: Notification system + payment gateway design. ByteByteGo Ch 1-5 read', status: 'Not Started' },
  { phase: 'Phase 3', week: 'Wk 16', weekNumber: 16, lcTarget: 168, mockInterviews: 0, githubProjects: 0, deliverable: 'LLD: Parking Lot in TypeScript (full implementation). Design patterns: Observer, Strategy, Factory', status: 'Not Started' },
  { phase: 'Phase 3', week: 'Wk 17', weekNumber: 17, lcTarget: 174, mockInterviews: 4, githubProjects: 1, deliverable: '2 mock system design interviews on Pramp. LinkedIn article: micro-frontend architecture', status: 'Not Started' },
  { phase: 'Phase 3', week: 'Wk 18', weekNumber: 18, lcTarget: 180, mockInterviews: 0, githubProjects: 0, deliverable: 'Frontend system design: RADIO framework. Practice: autocomplete, infinite scroll, chat, design system', status: 'Not Started' },
  // Phase 4
  { phase: 'Phase 4', week: 'Wk 19', weekNumber: 19, lcTarget: 186, mockInterviews: 0, githubProjects: 0, deliverable: 'DSA: Advanced graphs (Dijkstra, Bellman-Ford). 1 LeetCode contest', status: 'Not Started' },
  { phase: 'Phase 4', week: 'Wk 20', weekNumber: 20, lcTarget: 192, mockInterviews: 0, githubProjects: 0, deliverable: 'Machine coding: build infinite-scroll feed + autocomplete in React in 45 min each', status: 'Not Started' },
  { phase: 'Phase 4', week: 'Wk 21', weekNumber: 21, lcTarget: 198, mockInterviews: 0, githubProjects: 0, deliverable: 'Machine coding: kanban board + multi-step form. GreatFrontEnd practice problems', status: 'Not Started' },
  { phase: 'Phase 4', week: 'Wk 22', weekNumber: 22, lcTarget: 205, mockInterviews: 6, githubProjects: 0, deliverable: '3 timed mock interviews on Pramp. Wrong-answer review doc written', status: 'Not Started' },
  // Phase 5
  { phase: 'Phase 5', week: 'Wk 23', weekNumber: 23, lcTarget: 210, mockInterviews: 0, githubProjects: 2, deliverable: 'LLM feature live: Gemini+Groq dual-fallback in asset management app. Live demo URL', status: 'Not Started' },
  { phase: 'Phase 5', week: 'Wk 24', weekNumber: 24, lcTarget: 215, mockInterviews: 0, githubProjects: 3, deliverable: 'Azure Functions + Cosmos DB project on GitHub. NestJS + Azure Service Bus demo', status: 'Not Started' },
  { phase: 'Phase 5', week: 'Wk 25', weekNumber: 25, lcTarget: 220, mockInterviews: 0, githubProjects: 0, deliverable: 'AWS SAA study started (Andrew Brown free 14hr YouTube). EC2, S3, VPC, IAM basics', status: 'Not Started' },
  { phase: 'Phase 5', week: 'Wk 26', weekNumber: 26, lcTarget: 225, mockInterviews: 0, githubProjects: 0, deliverable: 'AWS SAA exam booked. Kubernetes: AKS deployment of NestJS project with Helm chart', status: 'Not Started' },
  { phase: 'Phase 5', week: 'Wk 27', weekNumber: 27, lcTarget: 230, mockInterviews: 7, githubProjects: 0, deliverable: 'AWS SAA exam taken. 3 mock system design + 4 mock coding sessions total this phase', status: 'Not Started' },
  // Phase 6
  { phase: 'Phase 6', week: 'Wk 28', weekNumber: 28, lcTarget: 235, mockInterviews: 0, githubProjects: 0, deliverable: 'Blog post 1: Single-SPA micro-frontend architecture deep dive (Hashnode + LinkedIn)', status: 'Not Started' },
  { phase: 'Phase 6', week: 'Wk 29', weekNumber: 29, lcTarget: 238, mockInterviews: 0, githubProjects: 0, deliverable: 'Blog post 2: LLM portfolio analysis with Gemini+Groq — no vector DB (Hashnode + LinkedIn)', status: 'Not Started' },
  { phase: 'Phase 6', week: 'Wk 30', weekNumber: 30, lcTarget: 241, mockInterviews: 0, githubProjects: 0, deliverable: 'OSS: 2 meaningful PRs to NestJS or Next.js repos (docs, tests, or small bug fix)', status: 'Not Started' },
  { phase: 'Phase 6', week: 'Wk 31', weekNumber: 31, lcTarget: 244, mockInterviews: 8, githubProjects: 0, deliverable: 'Blog post 3: interview experience post. AZ-305 study started. All 3 GitHub projects polished', status: 'Not Started' },
  // Phase 7
  { phase: 'Phase 7', week: 'Wk 32', weekNumber: 32, lcTarget: 247, mockInterviews: 0, githubProjects: 0, deliverable: '50 referral DMs sent to engineers at top 10 target companies. Book 2 more Topmate sessions', status: 'Not Started' },
  { phase: 'Phase 7', week: 'Wk 33', weekNumber: 33, lcTarget: 250, mockInterviews: 0, githubProjects: 0, deliverable: 'Full mock loop: coding (45min) + HLD (45min) + behavioral (30min). Apply all Tier A companies', status: 'Not Started' },
  { phase: 'Phase 7', week: 'Wk 34', weekNumber: 34, lcTarget: 253, mockInterviews: 0, githubProjects: 0, deliverable: 'STAR/STARR: 10 behavioral stories rehearsed on camera. Company research for top 5 done', status: 'Not Started' },
  { phase: 'Phase 7', week: 'Wk 35', weekNumber: 35, lcTarget: 256, mockInterviews: 10, githubProjects: 0, deliverable: '5+ interview loops in pipeline. Salary negotiation prep: AmbitionBox + Levels.fyi data captured', status: 'Not Started' },
  // Phase 8
  { phase: 'Phase 8', week: 'Wk 36', weekNumber: 36, lcTarget: 258, mockInterviews: 0, githubProjects: 0, deliverable: 'Active interviews: track every question asked within 30 min of each interview', status: 'Not Started' },
  { phase: 'Phase 8', week: 'Wk 37', weekNumber: 37, lcTarget: 260, mockInterviews: 0, githubProjects: 0, deliverable: 'Counter-offers: if PwC counters, politely decline. Always have 2+ competing offers before accepting', status: 'Not Started' },
  { phase: 'Phase 8', week: 'Wk 38', weekNumber: 38, lcTarget: 262, mockInterviews: 0, githubProjects: 0, deliverable: 'Negotiate every offer: fixed > joining bonus > ESOP > variable. Get buyout covered by new employer', status: 'Not Started' },
  { phase: 'Phase 8', week: 'Wk 39', weekNumber: 39, lcTarget: 265, mockInterviews: 0, githubProjects: 0, deliverable: 'Offer signed at Rs.28-35L+. PwC resignation submitted. Notice period plan confirmed', status: 'Not Started' },
]

// ── DSA Problems (162 problems) ───────────────────────────────────────────────
export const DSA_PROBLEMS_SEED: Omit<DSAProblem, 'id'>[] = [
  // Arrays & Hashing
  { name: 'Two Sum', pattern: 'Arrays', difficulty: 'Easy', url: 'https://leetcode.com/problems/two-sum/', status: 'To Do', notes: '' },
  { name: 'Contains Duplicate', pattern: 'Arrays', difficulty: 'Easy', url: 'https://leetcode.com/problems/contains-duplicate/', status: 'To Do', notes: '' },
  { name: 'Valid Anagram', pattern: 'Arrays', difficulty: 'Easy', url: 'https://leetcode.com/problems/valid-anagram/', status: 'To Do', notes: '' },
  { name: 'Group Anagrams', pattern: 'Arrays', difficulty: 'Medium', url: 'https://leetcode.com/problems/group-anagrams/', status: 'To Do', notes: '' },
  { name: 'Top K Frequent Elements', pattern: 'Arrays', difficulty: 'Medium', url: 'https://leetcode.com/problems/top-k-frequent-elements/', status: 'To Do', notes: '' },
  { name: 'Product of Array Except Self', pattern: 'Arrays', difficulty: 'Medium', url: 'https://leetcode.com/problems/product-of-array-except-self/', status: 'To Do', notes: '' },
  { name: 'Valid Sudoku', pattern: 'Arrays', difficulty: 'Medium', url: 'https://leetcode.com/problems/valid-sudoku/', status: 'To Do', notes: '' },
  { name: 'Encode and Decode Strings', pattern: 'Arrays', difficulty: 'Medium', url: 'https://leetcode.com/problems/encode-and-decode-strings/', status: 'To Do', notes: '' },
  { name: 'Longest Consecutive Sequence', pattern: 'Arrays', difficulty: 'Medium', url: 'https://leetcode.com/problems/longest-consecutive-sequence/', status: 'To Do', notes: '' },
  { name: 'Rotate Image', pattern: 'Arrays', difficulty: 'Medium', url: 'https://leetcode.com/problems/rotate-image/', status: 'To Do', notes: '' },
  { name: 'Spiral Matrix', pattern: 'Arrays', difficulty: 'Medium', url: 'https://leetcode.com/problems/spiral-matrix/', status: 'To Do', notes: '' },
  { name: 'Set Matrix Zeroes', pattern: 'Arrays', difficulty: 'Medium', url: 'https://leetcode.com/problems/set-matrix-zeroes/', status: 'To Do', notes: '' },
  { name: 'Happy Number', pattern: 'Arrays', difficulty: 'Easy', url: 'https://leetcode.com/problems/happy-number/', status: 'To Do', notes: '' },
  { name: 'Plus One', pattern: 'Arrays', difficulty: 'Easy', url: 'https://leetcode.com/problems/plus-one/', status: 'To Do', notes: '' },
  { name: 'Pow(x,n)', pattern: 'Arrays', difficulty: 'Medium', url: 'https://leetcode.com/problems/powx-n/', status: 'To Do', notes: '' },
  { name: 'Multiply Strings', pattern: 'Arrays', difficulty: 'Medium', url: 'https://leetcode.com/problems/multiply-strings/', status: 'To Do', notes: '' },
  { name: 'Detect Squares', pattern: 'Arrays', difficulty: 'Medium', url: 'https://leetcode.com/problems/detect-squares/', status: 'To Do', notes: '' },
  // Two Pointers
  { name: 'Valid Palindrome', pattern: 'Two Pointers', difficulty: 'Easy', url: 'https://leetcode.com/problems/valid-palindrome/', status: 'To Do', notes: '' },
  { name: 'Two Sum II Input Array Sorted', pattern: 'Two Pointers', difficulty: 'Medium', url: 'https://leetcode.com/problems/two-sum-ii-input-array-is-sorted/', status: 'To Do', notes: '' },
  { name: '3Sum', pattern: 'Two Pointers', difficulty: 'Medium', url: 'https://leetcode.com/problems/3sum/', status: 'To Do', notes: '' },
  { name: 'Container With Most Water', pattern: 'Two Pointers', difficulty: 'Medium', url: 'https://leetcode.com/problems/container-with-most-water/', status: 'To Do', notes: '' },
  { name: 'Trapping Rain Water', pattern: 'Two Pointers', difficulty: 'Hard', url: 'https://leetcode.com/problems/trapping-rain-water/', status: 'To Do', notes: '' },
  // Sliding Window
  { name: 'Best Time to Buy/Sell Stock', pattern: 'Sliding Window', difficulty: 'Easy', url: 'https://leetcode.com/problems/best-time-to-buy-and-sell-stock/', status: 'To Do', notes: '' },
  { name: 'Longest Substring Without Repeat', pattern: 'Sliding Window', difficulty: 'Medium', url: 'https://leetcode.com/problems/longest-substring-without-repeating-characters/', status: 'To Do', notes: '' },
  { name: 'Longest Repeating Character Replacement', pattern: 'Sliding Window', difficulty: 'Medium', url: 'https://leetcode.com/problems/longest-repeating-character-replacement/', status: 'To Do', notes: '' },
  { name: 'Permutation in String', pattern: 'Sliding Window', difficulty: 'Medium', url: 'https://leetcode.com/problems/permutation-in-string/', status: 'To Do', notes: '' },
  { name: 'Minimum Window Substring', pattern: 'Sliding Window', difficulty: 'Hard', url: 'https://leetcode.com/problems/minimum-window-substring/', status: 'To Do', notes: '' },
  { name: 'Sliding Window Maximum', pattern: 'Sliding Window', difficulty: 'Hard', url: 'https://leetcode.com/problems/sliding-window-maximum/', status: 'To Do', notes: '' },
  // Stack
  { name: 'Valid Parentheses', pattern: 'Stack', difficulty: 'Easy', url: 'https://leetcode.com/problems/valid-parentheses/', status: 'To Do', notes: '' },
  { name: 'Min Stack', pattern: 'Stack', difficulty: 'Medium', url: 'https://leetcode.com/problems/min-stack/', status: 'To Do', notes: '' },
  { name: 'Evaluate Reverse Polish Notation', pattern: 'Stack', difficulty: 'Medium', url: 'https://leetcode.com/problems/evaluate-reverse-polish-notation/', status: 'To Do', notes: '' },
  { name: 'Generate Parentheses', pattern: 'Stack', difficulty: 'Medium', url: 'https://leetcode.com/problems/generate-parentheses/', status: 'To Do', notes: '' },
  { name: 'Daily Temperatures', pattern: 'Stack', difficulty: 'Medium', url: 'https://leetcode.com/problems/daily-temperatures/', status: 'To Do', notes: '' },
  { name: 'Car Fleet', pattern: 'Stack', difficulty: 'Medium', url: 'https://leetcode.com/problems/car-fleet/', status: 'To Do', notes: '' },
  { name: 'Largest Rectangle in Histogram', pattern: 'Stack', difficulty: 'Hard', url: 'https://leetcode.com/problems/largest-rectangle-in-histogram/', status: 'To Do', notes: '' },
  // Binary Search
  { name: 'Binary Search', pattern: 'Binary Search', difficulty: 'Easy', url: 'https://leetcode.com/problems/binary-search/', status: 'To Do', notes: '' },
  { name: 'Search a 2D Matrix', pattern: 'Binary Search', difficulty: 'Medium', url: 'https://leetcode.com/problems/search-a-2d-matrix/', status: 'To Do', notes: '' },
  { name: 'Koko Eating Bananas', pattern: 'Binary Search', difficulty: 'Medium', url: 'https://leetcode.com/problems/koko-eating-bananas/', status: 'To Do', notes: '' },
  { name: 'Find Minimum in Rotated Sorted Array', pattern: 'Binary Search', difficulty: 'Medium', url: 'https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/', status: 'To Do', notes: '' },
  { name: 'Search in Rotated Sorted Array', pattern: 'Binary Search', difficulty: 'Medium', url: 'https://leetcode.com/problems/search-in-rotated-sorted-array/', status: 'To Do', notes: '' },
  { name: 'Time Based Key-Value Store', pattern: 'Binary Search', difficulty: 'Medium', url: 'https://leetcode.com/problems/time-based-key-value-store/', status: 'To Do', notes: '' },
  { name: 'Median of Two Sorted Arrays', pattern: 'Binary Search', difficulty: 'Hard', url: 'https://leetcode.com/problems/median-of-two-sorted-arrays/', status: 'To Do', notes: '' },
  // Linked List
  { name: 'Reverse Linked List', pattern: 'Linked List', difficulty: 'Easy', url: 'https://leetcode.com/problems/reverse-linked-list/', status: 'To Do', notes: '' },
  { name: 'Merge Two Sorted Lists', pattern: 'Linked List', difficulty: 'Easy', url: 'https://leetcode.com/problems/merge-two-sorted-lists/', status: 'To Do', notes: '' },
  { name: 'Reorder List', pattern: 'Linked List', difficulty: 'Medium', url: 'https://leetcode.com/problems/reorder-list/', status: 'To Do', notes: '' },
  { name: 'Remove Nth Node from End', pattern: 'Linked List', difficulty: 'Medium', url: 'https://leetcode.com/problems/remove-nth-node-from-end-of-list/', status: 'To Do', notes: '' },
  { name: 'Copy List with Random Pointer', pattern: 'Linked List', difficulty: 'Medium', url: 'https://leetcode.com/problems/copy-list-with-random-pointer/', status: 'To Do', notes: '' },
  { name: 'Add Two Numbers', pattern: 'Linked List', difficulty: 'Medium', url: 'https://leetcode.com/problems/add-two-numbers/', status: 'To Do', notes: '' },
  { name: 'Linked List Cycle', pattern: 'Linked List', difficulty: 'Easy', url: 'https://leetcode.com/problems/linked-list-cycle/', status: 'To Do', notes: '' },
  { name: 'Find the Duplicate Number', pattern: 'Linked List', difficulty: 'Medium', url: 'https://leetcode.com/problems/find-the-duplicate-number/', status: 'To Do', notes: '' },
  { name: 'LRU Cache', pattern: 'Linked List', difficulty: 'Medium', url: 'https://leetcode.com/problems/lru-cache/', status: 'To Do', notes: '' },
  { name: 'Merge K Sorted Lists', pattern: 'Linked List', difficulty: 'Hard', url: 'https://leetcode.com/problems/merge-k-sorted-lists/', status: 'To Do', notes: '' },
  { name: 'Reverse Nodes in K-Group', pattern: 'Linked List', difficulty: 'Hard', url: 'https://leetcode.com/problems/reverse-nodes-in-k-group/', status: 'To Do', notes: '' },
  // Trees
  { name: 'Invert Binary Tree', pattern: 'Trees', difficulty: 'Easy', url: 'https://leetcode.com/problems/invert-binary-tree/', status: 'To Do', notes: '' },
  { name: 'Maximum Depth of Binary Tree', pattern: 'Trees', difficulty: 'Easy', url: 'https://leetcode.com/problems/maximum-depth-of-binary-tree/', status: 'To Do', notes: '' },
  { name: 'Diameter of Binary Tree', pattern: 'Trees', difficulty: 'Easy', url: 'https://leetcode.com/problems/diameter-of-binary-tree/', status: 'To Do', notes: '' },
  { name: 'Balanced Binary Tree', pattern: 'Trees', difficulty: 'Easy', url: 'https://leetcode.com/problems/balanced-binary-tree/', status: 'To Do', notes: '' },
  { name: 'Same Tree', pattern: 'Trees', difficulty: 'Easy', url: 'https://leetcode.com/problems/same-tree/', status: 'To Do', notes: '' },
  { name: 'Subtree of Another Tree', pattern: 'Trees', difficulty: 'Easy', url: 'https://leetcode.com/problems/subtree-of-another-tree/', status: 'To Do', notes: '' },
  { name: 'Lowest Common Ancestor BST', pattern: 'Trees', difficulty: 'Medium', url: 'https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/', status: 'To Do', notes: '' },
  { name: 'Binary Tree Level Order Traversal', pattern: 'Trees', difficulty: 'Medium', url: 'https://leetcode.com/problems/binary-tree-level-order-traversal/', status: 'To Do', notes: '' },
  { name: 'Binary Tree Right Side View', pattern: 'Trees', difficulty: 'Medium', url: 'https://leetcode.com/problems/binary-tree-right-side-view/', status: 'To Do', notes: '' },
  { name: 'Count Good Nodes in Binary Tree', pattern: 'Trees', difficulty: 'Medium', url: 'https://leetcode.com/problems/count-good-nodes-in-binary-tree/', status: 'To Do', notes: '' },
  { name: 'Validate Binary Search Tree', pattern: 'Trees', difficulty: 'Medium', url: 'https://leetcode.com/problems/validate-binary-search-tree/', status: 'To Do', notes: '' },
  { name: 'Kth Smallest in BST', pattern: 'Trees', difficulty: 'Medium', url: 'https://leetcode.com/problems/kth-smallest-element-in-a-bst/', status: 'To Do', notes: '' },
  { name: 'Construct Binary Tree from Preorder Inorder', pattern: 'Trees', difficulty: 'Medium', url: 'https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal/', status: 'To Do', notes: '' },
  { name: 'Binary Tree Maximum Path Sum', pattern: 'Trees', difficulty: 'Hard', url: 'https://leetcode.com/problems/binary-tree-maximum-path-sum/', status: 'To Do', notes: '' },
  { name: 'Serialize and Deserialize Binary Tree', pattern: 'Trees', difficulty: 'Hard', url: 'https://leetcode.com/problems/serialize-and-deserialize-binary-tree/', status: 'To Do', notes: '' },
  // Heap
  { name: 'Kth Largest Element in Array', pattern: 'Heap', difficulty: 'Medium', url: 'https://leetcode.com/problems/kth-largest-element-in-an-array/', status: 'To Do', notes: '' },
  { name: 'Last Stone Weight', pattern: 'Heap', difficulty: 'Easy', url: 'https://leetcode.com/problems/last-stone-weight/', status: 'To Do', notes: '' },
  { name: 'K Closest Points to Origin', pattern: 'Heap', difficulty: 'Medium', url: 'https://leetcode.com/problems/k-closest-points-to-origin/', status: 'To Do', notes: '' },
  { name: 'Task Scheduler', pattern: 'Heap', difficulty: 'Medium', url: 'https://leetcode.com/problems/task-scheduler/', status: 'To Do', notes: '' },
  { name: 'Design Twitter', pattern: 'Heap', difficulty: 'Medium', url: 'https://leetcode.com/problems/design-twitter/', status: 'To Do', notes: '' },
  { name: 'Find Median from Data Stream', pattern: 'Heap', difficulty: 'Hard', url: 'https://leetcode.com/problems/find-median-from-data-stream/', status: 'To Do', notes: '' },
  // Backtracking
  { name: 'Subsets', pattern: 'Backtracking', difficulty: 'Medium', url: 'https://leetcode.com/problems/subsets/', status: 'To Do', notes: '' },
  { name: 'Combination Sum', pattern: 'Backtracking', difficulty: 'Medium', url: 'https://leetcode.com/problems/combination-sum/', status: 'To Do', notes: '' },
  { name: 'Permutations', pattern: 'Backtracking', difficulty: 'Medium', url: 'https://leetcode.com/problems/permutations/', status: 'To Do', notes: '' },
  { name: 'Subsets II', pattern: 'Backtracking', difficulty: 'Medium', url: 'https://leetcode.com/problems/subsets-ii/', status: 'To Do', notes: '' },
  { name: 'Combination Sum II', pattern: 'Backtracking', difficulty: 'Medium', url: 'https://leetcode.com/problems/combination-sum-ii/', status: 'To Do', notes: '' },
  { name: 'Word Search', pattern: 'Backtracking', difficulty: 'Medium', url: 'https://leetcode.com/problems/word-search/', status: 'To Do', notes: '' },
  { name: 'Palindrome Partitioning', pattern: 'Backtracking', difficulty: 'Medium', url: 'https://leetcode.com/problems/palindrome-partitioning/', status: 'To Do', notes: '' },
  { name: 'Letter Combinations of Phone Number', pattern: 'Backtracking', difficulty: 'Medium', url: 'https://leetcode.com/problems/letter-combinations-of-a-phone-number/', status: 'To Do', notes: '' },
  { name: 'N-Queens', pattern: 'Backtracking', difficulty: 'Hard', url: 'https://leetcode.com/problems/n-queens/', status: 'To Do', notes: '' },
  // Graphs
  { name: 'Number of Islands', pattern: 'Graphs', difficulty: 'Medium', url: 'https://leetcode.com/problems/number-of-islands/', status: 'To Do', notes: '' },
  { name: 'Max Area of Island', pattern: 'Graphs', difficulty: 'Medium', url: 'https://leetcode.com/problems/max-area-of-island/', status: 'To Do', notes: '' },
  { name: 'Clone Graph', pattern: 'Graphs', difficulty: 'Medium', url: 'https://leetcode.com/problems/clone-graph/', status: 'To Do', notes: '' },
  { name: 'Walls and Gates', pattern: 'Graphs', difficulty: 'Medium', url: 'https://leetcode.com/problems/walls-and-gates/', status: 'To Do', notes: '' },
  { name: 'Rotting Oranges', pattern: 'Graphs', difficulty: 'Medium', url: 'https://leetcode.com/problems/rotting-oranges/', status: 'To Do', notes: '' },
  { name: 'Pacific Atlantic Water Flow', pattern: 'Graphs', difficulty: 'Medium', url: 'https://leetcode.com/problems/pacific-atlantic-water-flow/', status: 'To Do', notes: '' },
  { name: 'Surrounded Regions', pattern: 'Graphs', difficulty: 'Medium', url: 'https://leetcode.com/problems/surrounded-regions/', status: 'To Do', notes: '' },
  { name: 'Course Schedule', pattern: 'Graphs', difficulty: 'Medium', url: 'https://leetcode.com/problems/course-schedule/', status: 'To Do', notes: '' },
  { name: 'Course Schedule II', pattern: 'Graphs', difficulty: 'Medium', url: 'https://leetcode.com/problems/course-schedule-ii/', status: 'To Do', notes: '' },
  { name: 'Number of Connected Components', pattern: 'Graphs', difficulty: 'Medium', url: 'https://leetcode.com/problems/number-of-connected-components-in-an-undirected-graph/', status: 'To Do', notes: '' },
  { name: 'Graph Valid Tree', pattern: 'Graphs', difficulty: 'Medium', url: 'https://leetcode.com/problems/graph-valid-tree/', status: 'To Do', notes: '' },
  { name: 'Redundant Connection', pattern: 'Graphs', difficulty: 'Medium', url: 'https://leetcode.com/problems/redundant-connection/', status: 'To Do', notes: '' },
  { name: 'Word Ladder', pattern: 'Graphs', difficulty: 'Hard', url: 'https://leetcode.com/problems/word-ladder/', status: 'To Do', notes: '' },
  { name: 'Reconstruct Itinerary', pattern: 'Graphs', difficulty: 'Hard', url: 'https://leetcode.com/problems/reconstruct-itinerary/', status: 'To Do', notes: '' },
  { name: 'Min Cost to Connect All Points', pattern: 'Graphs', difficulty: 'Medium', url: 'https://leetcode.com/problems/min-cost-to-connect-all-points/', status: 'To Do', notes: '' },
  { name: 'Network Delay Time', pattern: 'Graphs', difficulty: 'Medium', url: 'https://leetcode.com/problems/network-delay-time/', status: 'To Do', notes: '' },
  { name: 'Swim in Rising Water', pattern: 'Graphs', difficulty: 'Hard', url: 'https://leetcode.com/problems/swim-in-rising-water/', status: 'To Do', notes: '' },
  { name: 'Alien Dictionary', pattern: 'Graphs', difficulty: 'Hard', url: 'https://leetcode.com/problems/alien-dictionary/', status: 'To Do', notes: '' },
  { name: 'Cheapest Flights Within K Stops', pattern: 'Graphs', difficulty: 'Medium', url: 'https://leetcode.com/problems/cheapest-flights-within-k-stops/', status: 'To Do', notes: '' },
  // DP
  { name: 'Climbing Stairs', pattern: 'DP', difficulty: 'Easy', url: 'https://leetcode.com/problems/climbing-stairs/', status: 'To Do', notes: '' },
  { name: 'Min Cost Climbing Stairs', pattern: 'DP', difficulty: 'Easy', url: 'https://leetcode.com/problems/min-cost-climbing-stairs/', status: 'To Do', notes: '' },
  { name: 'House Robber', pattern: 'DP', difficulty: 'Medium', url: 'https://leetcode.com/problems/house-robber/', status: 'To Do', notes: '' },
  { name: 'House Robber II', pattern: 'DP', difficulty: 'Medium', url: 'https://leetcode.com/problems/house-robber-ii/', status: 'To Do', notes: '' },
  { name: 'Longest Palindromic Substring', pattern: 'DP', difficulty: 'Medium', url: 'https://leetcode.com/problems/longest-palindromic-substring/', status: 'To Do', notes: '' },
  { name: 'Palindromic Substrings', pattern: 'DP', difficulty: 'Medium', url: 'https://leetcode.com/problems/palindromic-substrings/', status: 'To Do', notes: '' },
  { name: 'Decode Ways', pattern: 'DP', difficulty: 'Medium', url: 'https://leetcode.com/problems/decode-ways/', status: 'To Do', notes: '' },
  { name: 'Coin Change', pattern: 'DP', difficulty: 'Medium', url: 'https://leetcode.com/problems/coin-change/', status: 'To Do', notes: '' },
  { name: 'Maximum Product Subarray', pattern: 'DP', difficulty: 'Medium', url: 'https://leetcode.com/problems/maximum-product-subarray/', status: 'To Do', notes: '' },
  { name: 'Word Break', pattern: 'DP', difficulty: 'Medium', url: 'https://leetcode.com/problems/word-break/', status: 'To Do', notes: '' },
  { name: 'Longest Increasing Subsequence', pattern: 'DP', difficulty: 'Medium', url: 'https://leetcode.com/problems/longest-increasing-subsequence/', status: 'To Do', notes: '' },
  { name: 'Partition Equal Subset Sum', pattern: 'DP', difficulty: 'Medium', url: 'https://leetcode.com/problems/partition-equal-subset-sum/', status: 'To Do', notes: '' },
  { name: 'Unique Paths', pattern: 'DP', difficulty: 'Medium', url: 'https://leetcode.com/problems/unique-paths/', status: 'To Do', notes: '' },
  { name: 'Longest Common Subsequence', pattern: 'DP', difficulty: 'Medium', url: 'https://leetcode.com/problems/longest-common-subsequence/', status: 'To Do', notes: '' },
  { name: 'Best Time Buy Sell Stock with Cooldown', pattern: 'DP', difficulty: 'Medium', url: 'https://leetcode.com/problems/best-time-to-buy-and-sell-stock-with-cooldown/', status: 'To Do', notes: '' },
  { name: 'Coin Change II', pattern: 'DP', difficulty: 'Medium', url: 'https://leetcode.com/problems/coin-change-ii/', status: 'To Do', notes: '' },
  { name: 'Target Sum', pattern: 'DP', difficulty: 'Medium', url: 'https://leetcode.com/problems/target-sum/', status: 'To Do', notes: '' },
  { name: 'Interleaving String', pattern: 'DP', difficulty: 'Medium', url: 'https://leetcode.com/problems/interleaving-string/', status: 'To Do', notes: '' },
  { name: 'Longest Increasing Path in Matrix', pattern: 'DP', difficulty: 'Hard', url: 'https://leetcode.com/problems/longest-increasing-path-in-a-matrix/', status: 'To Do', notes: '' },
  { name: 'Distinct Subsequences', pattern: 'DP', difficulty: 'Hard', url: 'https://leetcode.com/problems/distinct-subsequences/', status: 'To Do', notes: '' },
  { name: 'Edit Distance', pattern: 'DP', difficulty: 'Medium', url: 'https://leetcode.com/problems/edit-distance/', status: 'To Do', notes: '' },
  { name: 'Burst Balloons', pattern: 'DP', difficulty: 'Hard', url: 'https://leetcode.com/problems/burst-balloons/', status: 'To Do', notes: '' },
  { name: 'Regular Expression Matching', pattern: 'DP', difficulty: 'Hard', url: 'https://leetcode.com/problems/regular-expression-matching/', status: 'To Do', notes: '' },
  // Greedy
  { name: 'Maximum Subarray', pattern: 'Greedy', difficulty: 'Medium', url: 'https://leetcode.com/problems/maximum-subarray/', status: 'To Do', notes: '' },
  { name: 'Jump Game', pattern: 'Greedy', difficulty: 'Medium', url: 'https://leetcode.com/problems/jump-game/', status: 'To Do', notes: '' },
  { name: 'Jump Game II', pattern: 'Greedy', difficulty: 'Medium', url: 'https://leetcode.com/problems/jump-game-ii/', status: 'To Do', notes: '' },
  { name: 'Gas Station', pattern: 'Greedy', difficulty: 'Medium', url: 'https://leetcode.com/problems/gas-station/', status: 'To Do', notes: '' },
  { name: 'Hand of Straights', pattern: 'Greedy', difficulty: 'Medium', url: 'https://leetcode.com/problems/hand-of-straights/', status: 'To Do', notes: '' },
  { name: 'Merge Triplets to Form Target Triplet', pattern: 'Greedy', difficulty: 'Medium', url: 'https://leetcode.com/problems/merge-triplets-to-form-target-triplet/', status: 'To Do', notes: '' },
  { name: 'Partition Labels', pattern: 'Greedy', difficulty: 'Medium', url: 'https://leetcode.com/problems/partition-labels/', status: 'To Do', notes: '' },
  { name: 'Valid Parenthesis String', pattern: 'Greedy', difficulty: 'Medium', url: 'https://leetcode.com/problems/valid-parenthesis-string/', status: 'To Do', notes: '' },
  { name: 'Insert Interval', pattern: 'Greedy', difficulty: 'Medium', url: 'https://leetcode.com/problems/insert-interval/', status: 'To Do', notes: '' },
  { name: 'Merge Intervals', pattern: 'Greedy', difficulty: 'Medium', url: 'https://leetcode.com/problems/merge-intervals/', status: 'To Do', notes: '' },
  { name: 'Non-overlapping Intervals', pattern: 'Greedy', difficulty: 'Medium', url: 'https://leetcode.com/problems/non-overlapping-intervals/', status: 'To Do', notes: '' },
  { name: 'Meeting Rooms', pattern: 'Greedy', difficulty: 'Easy', url: 'https://leetcode.com/problems/meeting-rooms/', status: 'To Do', notes: '' },
  { name: 'Meeting Rooms II', pattern: 'Greedy', difficulty: 'Medium', url: 'https://leetcode.com/problems/meeting-rooms-ii/', status: 'To Do', notes: '' },
  { name: 'Minimum Interval to Include Each Query', pattern: 'Greedy', difficulty: 'Hard', url: 'https://leetcode.com/problems/minimum-interval-to-include-each-query/', status: 'To Do', notes: '' },
  // Trie
  { name: 'Implement Trie', pattern: 'Trie', difficulty: 'Medium', url: 'https://leetcode.com/problems/implement-trie-prefix-tree/', status: 'To Do', notes: '' },
  { name: 'Add and Search Word', pattern: 'Trie', difficulty: 'Medium', url: 'https://leetcode.com/problems/design-add-and-search-words-data-structure/', status: 'To Do', notes: '' },
  { name: 'Word Search II', pattern: 'Trie', difficulty: 'Hard', url: 'https://leetcode.com/problems/word-search-ii/', status: 'To Do', notes: '' },
  // Bit Manipulation
  { name: 'Single Number', pattern: 'Bit Manipulation', difficulty: 'Easy', url: 'https://leetcode.com/problems/single-number/', status: 'To Do', notes: '' },
  { name: 'Number of 1 Bits', pattern: 'Bit Manipulation', difficulty: 'Easy', url: 'https://leetcode.com/problems/number-of-1-bits/', status: 'To Do', notes: '' },
  { name: 'Counting Bits', pattern: 'Bit Manipulation', difficulty: 'Easy', url: 'https://leetcode.com/problems/counting-bits/', status: 'To Do', notes: '' },
  { name: 'Reverse Bits', pattern: 'Bit Manipulation', difficulty: 'Easy', url: 'https://leetcode.com/problems/reverse-bits/', status: 'To Do', notes: '' },
  { name: 'Missing Number', pattern: 'Bit Manipulation', difficulty: 'Easy', url: 'https://leetcode.com/problems/missing-number/', status: 'To Do', notes: '' },
  { name: 'Sum of Two Integers', pattern: 'Bit Manipulation', difficulty: 'Medium', url: 'https://leetcode.com/problems/sum-of-two-integers/', status: 'To Do', notes: '' },
  { name: 'Reverse Integer', pattern: 'Bit Manipulation', difficulty: 'Medium', url: 'https://leetcode.com/problems/reverse-integer/', status: 'To Do', notes: '' },
  // SQL
  { name: 'Combine Two Tables', pattern: 'SQL', difficulty: 'Easy', url: 'https://leetcode.com/problems/combine-two-tables/', status: 'To Do', notes: '' },
  { name: 'Second Highest Salary', pattern: 'SQL', difficulty: 'Medium', url: 'https://leetcode.com/problems/second-highest-salary/', status: 'To Do', notes: '' },
  { name: 'Rank Scores', pattern: 'SQL', difficulty: 'Medium', url: 'https://leetcode.com/problems/rank-scores/', status: 'To Do', notes: '' },
  { name: 'Consecutive Numbers', pattern: 'SQL', difficulty: 'Medium', url: 'https://leetcode.com/problems/consecutive-numbers/', status: 'To Do', notes: '' },
  { name: 'Department Top Three Salaries', pattern: 'SQL', difficulty: 'Hard', url: 'https://leetcode.com/problems/department-top-three-salaries/', status: 'To Do', notes: '' },
  { name: 'Delete Duplicate Emails', pattern: 'SQL', difficulty: 'Easy', url: 'https://leetcode.com/problems/delete-duplicate-emails/', status: 'To Do', notes: '' },
  { name: 'Rising Temperature', pattern: 'SQL', difficulty: 'Easy', url: 'https://leetcode.com/problems/rising-temperature/', status: 'To Do', notes: '' },
  { name: 'Employees Earning More Than Managers', pattern: 'SQL', difficulty: 'Easy', url: 'https://leetcode.com/problems/employees-earning-more-than-their-managers/', status: 'To Do', notes: '' },
  { name: 'Find Duplicate Emails', pattern: 'SQL', difficulty: 'Easy', url: 'https://leetcode.com/problems/duplicate-emails/', status: 'To Do', notes: '' },
  { name: 'Customer Who Never Orders', pattern: 'SQL', difficulty: 'Easy', url: 'https://leetcode.com/problems/customers-who-never-order/', status: 'To Do', notes: '' },
  { name: 'Department Highest Salary', pattern: 'SQL', difficulty: 'Medium', url: 'https://leetcode.com/problems/department-highest-salary/', status: 'To Do', notes: '' },
  { name: 'Nth Highest Salary', pattern: 'SQL', difficulty: 'Medium', url: 'https://leetcode.com/problems/nth-highest-salary/', status: 'To Do', notes: '' },
  { name: 'Trips and Users', pattern: 'SQL', difficulty: 'Hard', url: 'https://leetcode.com/problems/trips-and-users/', status: 'To Do', notes: '' },
]

// ── Skills (12 skills) ────────────────────────────────────────────────────────
export const SKILLS_SEED: Omit<Skill, 'id'>[] = [
  {
    category: 'Infrastructure',
    name: 'Docker + Kubernetes',
    why: 'Baseline expectation at your level. Learn: Dockerfile, multi-stage builds, docker-compose, K8s Pods/Deployments/Services/Ingress, ConfigMaps, kubectl, Helm. Deploy one project to AKS.',
    targetCompanies: ['Wells Fargo', 'JPMorgan', 'Microsoft IDC', 'Razorpay', 'CRED'],
    resource: 'https://kodekloud.com/courses/kubernetes-for-the-absolute-beginners-hands-on/',
    resourceLabel: 'KodeKloud free K8s course',
    priority: 'Critical',
    status: 'Not Started',
  },
  {
    category: 'Infrastructure',
    name: 'Redis + Caching Patterns',
    why: 'Required for system design rounds. Learn: cache-aside, write-through, TTL/eviction (LRU/LFU), hot-key problem, cache stampede, Redis data structures, distributed locks (SET NX PX), pub/sub vs Streams.',
    targetCompanies: ['Razorpay', 'JPMorgan', 'Freshworks', 'CRED', 'Wells Fargo'],
    resource: 'https://www.hellointerview.com/learn/system-design/deep-dives/redis',
    resourceLabel: 'Hello Interview Redis Deep Dive (free)',
    priority: 'Critical',
    status: 'Not Started',
  },
  {
    category: 'Infrastructure',
    name: 'Kafka / Message Queues',
    why: 'BFSI and fintech use Kafka for payments, fraud detection, audit logs. Learn: producer/consumer/broker, topics/partitions, offsets, at-least-once vs exactly-once, Kafka vs RabbitMQ trade-offs.',
    targetCompanies: ['Wells Fargo', 'JPMorgan', 'UBS', 'Vanguard', 'Razorpay', 'Mastercard'],
    resource: 'https://developer.confluent.io/courses/apache-kafka/events/',
    resourceLabel: 'Confluent Kafka 101 (free)',
    priority: 'Critical',
    status: 'Not Started',
  },
  {
    category: 'API Design',
    name: 'GraphQL + Apollo',
    why: 'Expected at Postman, Freshworks, Hasura, CRED. Learn: schema/types/resolvers, queries/mutations/subscriptions, N+1 + DataLoader, persisted queries, Apollo Federation, authorization patterns.',
    targetCompanies: ['Postman', 'Freshworks', 'Hasura', 'CRED', 'Morgan Stanley'],
    resource: 'https://blog.postman.com/graphql-interview-questions/',
    resourceLabel: 'Postman GraphQL Interview Questions (free)',
    priority: 'High',
    status: 'Not Started',
  },
  {
    category: 'Testing',
    name: 'Playwright E2E Testing',
    why: 'Product companies expect E2E coverage beyond Vitest. Playwright: 45% industry adoption, TypeScript-native, cross-browser. Write 8+ tests for Next.js app covering login, dashboard, error states, accessibility.',
    targetCompanies: ['Postman', 'Freshworks', 'Salesforce', 'Microsoft IDC'],
    resource: 'https://playwright.dev/docs',
    resourceLabel: 'Playwright official docs (free)',
    priority: 'High',
    status: 'Not Started',
  },
  {
    category: 'Database',
    name: 'SQL Deep Practice (Window Functions, CTEs)',
    why: 'Wells Fargo HackerRank includes 2 DEEP SQL questions. Learn: ROW_NUMBER, RANK, DENSE_RANK, LAG, LEAD, CTEs, recursive CTEs, EXPLAIN/query plan, indexing strategies, complex joins.',
    targetCompanies: ['Wells Fargo', 'JPMorgan', 'Goldman Sachs', 'Mastercard'],
    resource: 'https://leetcode.com/studyplan/top-sql-50/',
    resourceLabel: 'LeetCode SQL 50 Study Plan (free)',
    priority: 'High',
    status: 'Not Started',
  },
  {
    category: 'Frontend',
    name: 'Frontend System Design (RADIO Framework)',
    why: 'Separate from backend HLD. RADIO = Requirements, Architecture, Data model, Interface/API, Optimisations. Practice: autocomplete, infinite scroll, real-time chat, collaborative editor, micro-frontend orchestration.',
    targetCompanies: ['Postman', 'Salesforce', 'Microsoft IDC', 'Freshworks', 'CRED'],
    resource: 'https://www.frontendinterviewhandbook.com/front-end-system-design',
    resourceLabel: 'Frontend Interview Handbook SD (free)',
    priority: 'High',
    status: 'Not Started',
  },
  {
    category: 'Cloud',
    name: 'AWS SAA-C03 Certification',
    why: 'Half of Indian product companies (Postman, CRED, Razorpay) run on AWS not Azure. SAA-C03 covers EC2, S3, RDS, VPC, IAM, Lambda, CloudFront, SQS, SNS.',
    targetCompanies: ['Postman', 'CRED', 'Razorpay', 'Vanguard', 'Atlassian'],
    resource: 'https://www.youtube.com/watch?v=Ia-UEYYR44s',
    resourceLabel: 'Andrew Brown freeCodeCamp SAA (free, 14hrs)',
    priority: 'High',
    status: 'Not Started',
  },
  {
    category: 'Cloud',
    name: 'AZ-305 Azure Solutions Architect',
    why: 'Natural follow-on to AZ-204. Signals system design ability for architecture decisions. Covers multi-region HA, security, cost optimisation. High weight at BFSI GCCs.',
    targetCompanies: ['Wells Fargo', 'JPMorgan', 'Microsoft IDC', 'Mastercard', 'HSBC'],
    resource: 'https://learn.microsoft.com/en-us/training/azure/',
    resourceLabel: 'Microsoft Learn free AZ-305 paths',
    priority: 'Medium',
    status: 'Not Started',
  },
  {
    category: 'Java',
    name: 'Java Basics for BFSI Interviews',
    why: 'JPMorgan/Goldman/Morgan Stanley interview in Java. Know: HashMap internals, ConcurrentHashMap, ArrayList vs LinkedList, Streams/lambdas, threading basics. Be able to read and debug Java code.',
    targetCompanies: ['JPMorgan', 'Goldman Sachs', 'Morgan Stanley', 'Wells Fargo'],
    resource: 'https://www.baeldung.com/java-hashmap',
    resourceLabel: 'Baeldung Java tutorials (free)',
    priority: 'Medium',
    status: 'Not Started',
  },
  {
    category: 'Observability',
    name: 'Sentry / OpenTelemetry / APM',
    why: 'Common follow-up in design rounds: how to debug 10% checkout failure in prod? Add Sentry to Next.js project. Know: distributed tracing, structured logging, alerting thresholds, APM basics.',
    targetCompanies: ['Razorpay', 'Postman', 'Freshworks', 'Microsoft IDC'],
    resource: 'https://docs.sentry.io/',
    resourceLabel: 'Sentry docs (free)',
    priority: 'Medium',
    status: 'Not Started',
  },
  {
    category: 'OSS',
    name: 'Open Source Contributions (3-5 PRs)',
    why: '2-3 merged PRs to NestJS, Next.js, Single-SPA, or popular .NET 8 libs. Focus on docs, test coverage, small bug fixes. Avoid Hacktoberfest filler. Mention in resume and every interview.',
    targetCompanies: ['All product companies'],
    resource: 'https://github.com/nestjs/nest/issues?q=label%3A%22good+first+issue%22',
    resourceLabel: 'NestJS good first issues',
    priority: 'Medium',
    status: 'Not Started',
  },
]

// ── Tactics (21 tactics) ──────────────────────────────────────────────────────
export const TACTICS_SEED: Omit<Tactic, 'id'>[] = [
  { category: 'Platforms', name: 'Sign up on Instahyre', detail: 'AI-matched, hidden from current employer, low spam. Best for 3-7 YOE product/GCC roles. Fill 100% profile. Set expected CTC to blank/negotiable.', link: 'https://www.instahyre.com/', done: 'No' },
  { category: 'Platforms', name: 'Sign up on Hirist.tech', detail: 'Exclusively IT/tech. Premium unicorn listings (Dream11, Flipkart, Swiggy). Good for product roles not on LinkedIn.', link: 'https://hirist.tech/', done: 'No' },
  { category: 'Platforms', name: 'Sign up on Cutshort', detail: 'AI-driven matching. Many roles close in 48hrs. Verified skill badge improves match score.', link: 'https://cutshort.io/', done: 'No' },
  { category: 'Platforms', name: 'Sign up on Wellfound (AngelList)', detail: 'Best for startups and SaaS with ESOPs. Founders often personally review profiles.', link: 'https://wellfound.com/jobs', done: 'No' },
  { category: 'Platforms', name: 'Sign up on Peerlist', detail: 'Indian-founded developer network with startup job board. Verified profiles. Growing fast in 2025-2026.', link: 'https://peerlist.io/', done: 'No' },
  { category: 'Platforms', name: 'Sign up on Grapevine', detail: "India's largest anonymous career community. 400K+ professionals. Use for salary intel, PwC counter-offer reconnaissance, referral threads.", link: 'https://www.grapevine.in/', done: 'No' },
  { category: 'Community', name: 'Join r/developersIndia Discord', detail: '20,880+ members. Dedicated referral channel. Read the referral wiki before posting.', link: 'https://discord.com/invite/developersindia-669880381649977354', done: 'No' },
  { category: 'Community', name: 'Join Fishbowl PwC India Bowl', detail: 'Monitor for PwC counter-offer patterns, promotions cycle, bench situation. Critical for timing your resignation.', link: 'https://www.fishbowlapp.com/', done: 'No' },
  { category: 'Community', name: 'Join Telegram job channels', detail: '@indiareferraljobs for referral emails. Verify all roles before sharing info.', link: 'https://t.me/indiareferraljobs', done: 'No' },
  { category: 'Referrals', name: 'Topmate sessions at target companies', detail: 'Book 30-min sessions with engineers at top 5 target companies. Get referral link OR insider prep tips. Budget Rs.5000 total. Highest ROI spend.', link: 'https://topmate.io/', done: 'No' },
  { category: 'Referrals', name: 'LinkedIn DM campaign (30 DMs/month)', detail: "Template: 'Hi [Name], I am a Full-Stack Engineer (React/Node.js/.NET 8/Single-SPA/AZ-204, 4 YOE at PwC India, NIT Trichy). Applying for [exact Job ID]. Would you be open to a quick chat?' Max 4 sentences.", link: 'https://www.linkedin.com/jobs', done: 'No' },
  { category: 'Referrals', name: 'NIT Trichy alumni campaign (20 DMs)', detail: 'Search NIT Trichy on LinkedIn, filter by your top 10 companies. Send personalised DMs with specific job ID. Alumni connections convert at 3-5x cold DMs.', link: 'https://www.linkedin.com/search/results/people/', done: 'No' },
  { category: 'GitHub', name: 'Profile README + pinned repos with live URLs', detail: 'Add GitHub profile README with tech stack badges and contribution graph. Pin 4 repos with Vercel/Azure deployment URLs. Good commit messages 10-70 chars.', link: 'https://github.com/anuraghazra/github-readme-stats', done: 'No' },
  { category: 'GitHub', name: 'Contribute to 2-3 OSS repos (3-5 PRs merged)', detail: 'Target: NestJS, Next.js, Single-SPA. Focus on docs, tests, small bug fixes. Avoid Hacktoberfest filler. Mention in resume and every interview.', link: 'https://github.com/nestjs/nest/contribute', done: 'No' },
  { category: 'Content', name: 'Publish 4-6 posts on Hashnode over 9 months', detail: 'Posts titled "[Company] interview experience" rank on Google and drive recruiter DMs. Topics: Single-SPA architecture, interview experiences, Next.js+NestJS walkthrough, LLM integration tutorial.', link: 'https://hashnode.com/', done: 'No' },
  { category: 'Content', name: 'Cross-post every Hashnode article to LinkedIn', detail: 'Post LinkedIn version 3 days after Hashnode. Tag 2-3 engineers at target companies. Add hashtags: #reactjs #nextjs #nodejs #hyderabadjobs', link: 'https://www.linkedin.com/feed/', done: 'No' },
  { category: 'Salary Intel', name: 'Build AmbitionBox + Levels.fyi benchmark doc', detail: 'For each target company capture: median fixed CTC, total comp range, variable%, typical joining bonus. Use as negotiation anchor. Always quote market rate not current CTC.', link: 'https://www.ambitionbox.com/salaries', done: 'No' },
  { category: 'Negotiation', name: 'Salary negotiation script — memorise and rehearse', detail: "Script: 'Thank you for the offer. Based on market data from Levels.fyi showing Rs.X-Y for this profile in Hyderabad, and my background in Single-SPA/AZ-204/.NET 8, I was hoping for Rs.[anchor]. Is there flexibility on fixed CTC or joining bonus?'", link: 'https://haseebq.com/my-ten-rules-for-negotiating-a-job-offer/', done: 'No' },
  { category: 'Negotiation', name: 'PwC notice period + buyout strategy', detail: 'PwC India notice = 90 days. Buyout formula: (Monthly Gross/30) x Days = approx Rs.1.9L for 60 days. Ask new employer to cover as joining bonus.', link: 'https://www.glassdoor.co.in/Community/pwc-india-bowl', done: 'No' },
  { category: 'Negotiation', name: 'Form 16 / CTC disclosure handling', detail: "Script if pressed: 'My current fixed is Rs.11.3L, total Rs.14.5L. Given my experience in Single-SPA/AZ-204/.NET 8, I am targeting Rs.X which aligns with market benchmarks.' Never inflate.", link: 'https://www.ambitionbox.com/salaries', done: 'No' },
  { category: 'Financial', name: 'ESOP valuation comparison framework', detail: 'Discount Indian unicorn ESOPs: 50-70% for late-stage (Razorpay, CRED), 80-90% for early-stage. Confirm vesting cliff (1yr) and buyback history. Rule: Rs.24L fixed + Rs.40L ESOP ≈ Rs.26-28L fixed at stable GCC.', link: 'https://razorpay.com/newsroom/', done: 'No' },
]

// ── Prep entries (13 entries) ─────────────────────────────────────────────────
export const PREP_SEED: Omit<PrepEntry, 'id'>[] = [
  {
    section: 'Company Patterns',
    company: 'Wells Fargo Hyderabad',
    whatToPrepare: 'HackerRank: 1 algo + 1 Angular/JS problem + 2 DEEP SQL questions (window functions, CTEs, recursive). Multi-threading, HashMap collision resolution in technicals. Heavy behavioral rounds. 5-6 total rounds.',
    reportedQuestions: 'SQL: RANK vs DENSE_RANK vs ROW_NUMBER with gaps | HashMap collision resolution | Microservice architecture for payments | Tell me about a time you disagreed with your team lead | Spring Boot vs .NET trade-offs',
  },
  {
    section: 'Company Patterns',
    company: 'JPMorgan Chase Hyderabad',
    whatToPrepare: 'HackerRank OA: aptitude + LeetCode easy-medium-hard. Technical: Java internals, REST APIs, system design. 4-6 rounds. Narrate thinking aloud even when interviewer is silent.',
    reportedQuestions: 'Fraud detection system design | Global payment processing HLD | Java ConcurrentHashMap internals | Rate limiter with Redis | Difference between REST and GraphQL | Idempotency in distributed systems',
  },
  {
    section: 'Company Patterns',
    company: 'Microsoft IDC Hyderabad (SDE-II)',
    whatToPrepare: 'Codility/HackerRank OA + 3 technical rounds (1hr each) + AA veto round. DSA: trees, graphs, linked lists, DP. STARR format with Reflection. Growth-mindset signals heavily weighted.',
    reportedQuestions: 'LRU Cache from scratch | Design Twitter fan-out | Reverse linked list in K groups | Word Ladder BFS | Tell me about your biggest failure and what you learned',
  },
  {
    section: 'Company Patterns',
    company: 'Salesforce Hyderabad (MTS)',
    whatToPrepare: 'HackerRank: 2 DSA (medium-hard, often graphs/DP). 2 virtual rounds same day: JS output prediction + deep project/DBMS/OS. AI-first workflow explicitly evaluated.',
    reportedQuestions: 'Topological sort / Course Schedule | Flatten nested object in JS | ACID properties in SQL | How do you review AI-generated code? | Design multi-tenant SaaS authorization system',
  },
  {
    section: 'Company Patterns',
    company: 'Razorpay (SDE-II / Senior SWE)',
    whatToPrepare: 'No whiteboard trivia. Real IDE coding, design patterns, HLD+LLD. Product thinking and modularity weighted heavily. 5 rounds: recruiter screen > technical > HLD > Hiring Manager > Bar Raiser.',
    reportedQuestions: 'Logger framework LLD (Factory + Observer) | Fraud detection system | Rate limiter with Redis | Factory vs Strategy pattern with real example | Design Razorpay payment gateway end-to-end',
  },
  {
    section: 'Company Patterns',
    company: 'Postman (Software Engineer II Frontend)',
    whatToPrepare: 'Heavy API design knowledge required. Machine coding round (take-home or live 45 min). Deep React/TS performance. Knowledge of Postman product expected.',
    reportedQuestions: 'Build autocomplete in 45 min | How does Postman handle large API collections? | Implement React Query caching from scratch | GraphQL vs REST for API testing | How to design Postman variable/environment system?',
  },
  {
    section: 'Company Patterns',
    company: 'Freshworks (Staff Engineer Frontend)',
    whatToPrepare: 'Multiple rounds: coding + system design + micro-frontend depth + RFC-writing ability. Cross-team impact stories required at Staff level. Expect 5-6 rounds.',
    reportedQuestions: 'Micro-frontend architecture for Freshdesk | React rendering optimisation (your 40% re-render story) | Design a reusable component library | How do you write an RFC? | How do you mentor junior engineers?',
  },
  {
    section: 'Frontend System Design',
    company: 'RADIO Framework — must practice out loud',
    whatToPrepare: 'Requirements > Architecture > Data model > Interface/API > Optimisations. Lead every answer with "Let me clarify requirements." Practice 45 min per problem. Strong area due to your Single-SPA experience.',
    reportedQuestions: 'Autocomplete/typeahead | Infinite-scroll social feed | Real-time collaborative editor | Photo gallery with virtualisation | Multi-step checkout form | Design system/component library | Micro-frontend orchestration',
  },
  {
    section: 'Behavioral',
    company: 'STARR Stories — 10 prepared, 4 formats',
    whatToPrepare: 'Prepare 10 stories in STARR (Microsoft), SOAR, CAR, and STAR formats. Each story 90 seconds or 4 minutes. Always add Reflection for Microsoft. Use real metrics: 40% re-renders, 65% sprint velocity, 87% test coverage.',
    reportedQuestions: 'Performance improvement (40% re-renders reduction) | Process innovation (Cursor/Copilot 65% sprint boost) | Technical disagreement with manager | Biggest failure + what you learned | Decision with incomplete data | Cross-team collaboration',
  },
  {
    section: 'Negotiation',
    company: 'Salary Script — rehearse out loud 5 times',
    whatToPrepare: 'Never accept first offer verbally on the call. Always ask for 24-48 hours. Anchor 15-20% above their offer. Push: Fixed > Joining Bonus > ESOP > Variable guarantee > Notice buyout reimbursement.',
    reportedQuestions: "Script: 'Thank you for the offer. Based on market data from Levels.fyi showing Rs.X-Y for this profile in Hyderabad, and my experience in Single-SPA/AZ-204/.NET 8, I was hoping for Rs.[anchor]. Is there flexibility on fixed CTC, joining bonus, or ESOP grant?'",
  },
  {
    section: 'Negotiation',
    company: 'PwC Notice Period + Buyout Strategy',
    whatToPrepare: 'PwC India standard notice = 90 days. Check your offer letter for exact duration. Buyout formula: (Monthly Gross/30) x Remaining Days = approx Rs.1.88L for 60 days. Ask new employer to cover as joining bonus.',
    reportedQuestions: "Email script: 'I have a 90-day notice period at PwC. Would you include a joining bonus to cover the notice buyout of approx Rs.1.9L? This is standard for senior offers at this band.' Most GCCs agree.",
  },
  {
    section: 'Financial',
    company: 'ESOP Valuation and Comparison Math',
    whatToPrepare: 'Discount Indian unicorn ESOPs: 50-70% for late-stage, 80-90% for early-stage. Confirm: 1-year cliff + 4-year vest, buyback history, strike price vs current 409A valuation.',
    reportedQuestions: "Comparison: Rs.24L fixed + Rs.40L ESOP paper (4yr, late-stage unicorn) ≈ Rs.26-28L fixed at stable GCC after 60% discount + perquisite tax. Always ask: what is the current strike price, last 409A valuation, and have you done any secondary/buyback events?",
  },
  {
    section: 'Financial',
    company: 'Form 16 / CTC Disclosure Handling',
    whatToPrepare: 'Not legally required to disclose but verified at offer stage via Form 16/payslips. Never inflate. Script for deflecting: "I prefer to share my expectations for this role rather than my current CTC."',
    reportedQuestions: "If pressed: 'My current fixed is Rs.11.3L, total CTC Rs.14.5L. Given my achievements in micro-frontends, Azure AZ-204, and .NET 8, I am targeting Rs.X which aligns with AmbitionBox benchmarks for this role.'",
  },
]

// ── Resources (80+ resources) ─────────────────────────────────────────────────
export const RESOURCES_SEED: Omit<Resource, 'id'>[] = [
  { category: 'DSA', name: 'NeetCode 150 Roadmap', type: 'Structured roadmap', url: 'https://neetcode.io/roadmap' },
  { category: 'DSA', name: 'Striver A-Z DSA Sheet', type: 'Problem list + videos', url: 'https://takeuforward.org/strivers-a2z-dsa-course/strivers-a2z-dsa-course-sheet-2/' },
  { category: 'DSA', name: 'LeetCode Top Interview 150', type: 'Study plan', url: 'https://leetcode.com/studyplan/top-interview-150/' },
  { category: 'DSA', name: 'LeetCode SQL 50 Study Plan', type: 'SQL practice', url: 'https://leetcode.com/studyplan/top-sql-50/' },
  { category: 'DSA', name: 'Visualgo — data structure visualiser', type: 'Visualiser tool', url: 'https://visualgo.net/en' },
  { category: 'DSA', name: 'Big-O Cheat Sheet', type: 'Reference card', url: 'https://www.bigocheatsheet.com/' },
  { category: 'DSA', name: 'NeetCode YouTube channel', type: 'Video solutions free', url: 'https://www.youtube.com/@NeetCode' },
  { category: 'DSA', name: 'Pramp — free peer mock interviews', type: 'Free mock interviews', url: 'https://www.pramp.com/' },
  { category: 'DSA', name: 'Interviewing.io', type: 'Anonymous mocks with engineers', url: 'https://interviewing.io/' },
  { category: 'DSA', name: 'Topmate.io — paid referral + mock sessions', type: 'Rs.300-3000 per session', url: 'https://topmate.io/' },
  { category: 'DSA', name: 'freeCodeCamp JS Algorithms', type: 'Free course', url: 'https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/' },
  { category: 'Next.js', name: 'Next.js 15 Official Docs', type: 'Official docs', url: 'https://nextjs.org/docs' },
  { category: 'Next.js', name: 'Next.js Learn Course (official)', type: 'Free interactive course', url: 'https://nextjs.org/learn' },
  { category: 'Next.js', name: 'Fireship Next.js crash course', type: 'YouTube free', url: 'https://www.youtube.com/watch?v=__mSgDEOyv8' },
  { category: 'Next.js', name: 'Theo t3.gg — App Router deep dives', type: 'YouTube free', url: 'https://www.youtube.com/@t3dotgg' },
  { category: 'Next.js', name: 'Server Actions docs', type: 'Docs section', url: 'https://nextjs.org/docs/app/building-your-application/data-fetching/server-actions-and-mutations' },
  { category: 'NestJS', name: 'NestJS Official Docs', type: 'Official docs', url: 'https://docs.nestjs.com/' },
  { category: 'NestJS', name: 'NestJS free official course', type: 'Video course free', url: 'https://courses.nestjs.com/' },
  { category: 'NestJS', name: 'Traversy NestJS crash course', type: 'YouTube free', url: 'https://www.youtube.com/watch?v=wqhNoDE6pb4' },
  { category: 'NestJS', name: 'NestJS GraphQL docs', type: 'Docs', url: 'https://docs.nestjs.com/graphql/quick-start' },
  { category: 'NestJS', name: 'Prisma ORM Docs', type: 'ORM docs', url: 'https://www.prisma.io/docs' },
  { category: 'Infrastructure', name: 'KodeKloud free Kubernetes course', type: 'Free K8s course', url: 'https://kodekloud.com/courses/kubernetes-for-the-absolute-beginners-hands-on/' },
  { category: 'Infrastructure', name: 'Play with Kubernetes (free lab)', type: 'Free K8s playground', url: 'https://labs.play-with-k8s.com/' },
  { category: 'Infrastructure', name: 'Hello Interview Redis Deep Dive', type: 'Free deep dive', url: 'https://www.hellointerview.com/learn/system-design/deep-dives/redis' },
  { category: 'Infrastructure', name: 'Redis free tier playground', type: 'Free Redis instance', url: 'https://redis.io/try-free/' },
  { category: 'Infrastructure', name: 'Confluent Kafka 101 (free course)', type: 'Free Kafka course', url: 'https://developer.confluent.io/courses/apache-kafka/events/' },
  { category: 'Infrastructure', name: 'Hello Interview Kafka vs RabbitMQ', type: 'Free guide', url: 'https://www.hellointerview.com/blog/kafka-vs-rabbitmq' },
  { category: 'API Design', name: 'Postman GraphQL Interview Questions', type: 'Free guide', url: 'https://blog.postman.com/graphql-interview-questions/' },
  { category: 'API Design', name: 'Apollo GraphQL Docs', type: 'Official docs', url: 'https://www.apollographql.com/docs/' },
  { category: 'System Design', name: 'ByteByteGo System Design 101', type: 'Free GitHub repo', url: 'https://github.com/ByteByteGoHq/system-design-101' },
  { category: 'System Design', name: 'System Design Primer (260k stars)', type: 'Free GitHub repo', url: 'https://github.com/donnemartin/system-design-primer' },
  { category: 'System Design', name: 'Gaurav Sen System Design YouTube', type: 'Free video lectures', url: 'https://www.youtube.com/@gkcs' },
  { category: 'System Design', name: 'ByteByteGo YouTube', type: 'Free video lectures', url: 'https://www.youtube.com/@ByteByteGo' },
  { category: 'System Design', name: 'Excalidraw — HLD diagram tool', type: 'Free whiteboard', url: 'https://excalidraw.com/' },
  { category: 'System Design', name: 'Refactoring Guru Design Patterns', type: 'Free patterns guide', url: 'https://refactoring.guru/design-patterns' },
  { category: 'System Design', name: 'Arsh Goyal LLD Playlist', type: 'Free YouTube LLD', url: 'https://www.youtube.com/playlist?list=PLKZaSt2df1gz775Mz-2gLpY9sld5YOi4X' },
  { category: 'System Design', name: 'Frontend Interview Handbook SD', type: 'Free frontend SD', url: 'https://www.frontendinterviewhandbook.com/front-end-system-design' },
  { category: 'System Design', name: 'GreatFrontEnd system design', type: 'Free tier SD problems', url: 'https://www.greatfrontend.com/system-design' },
  { category: 'System Design', name: 'Hello Interview system design', type: 'Free guides + deep dives', url: 'https://www.hellointerview.com/' },
  { category: 'Testing', name: 'Playwright official docs', type: 'Free docs', url: 'https://playwright.dev/docs' },
  { category: 'Testing', name: 'Vitest docs', type: 'Free docs', url: 'https://vitest.dev/' },
  { category: 'Testing', name: 'React Testing Library docs', type: 'Free docs', url: 'https://testing-library.com/docs/react-testing-library/intro/' },
  { category: 'AI / LLM', name: 'Gemini API Docs + free key', type: 'Docs + free key', url: 'https://ai.google.dev/gemini-api/docs' },
  { category: 'AI / LLM', name: 'Groq API Docs + free key', type: 'Docs + free key (fastest)', url: 'https://console.groq.com/docs/openai' },
  { category: 'AI / LLM', name: 'Vercel AI SDK — LLM streaming', type: 'Free SDK docs', url: 'https://sdk.vercel.ai/docs/introduction' },
  { category: 'AI / LLM', name: 'LangChain JS Docs', type: 'Free orchestration', url: 'https://js.langchain.com/docs/introduction/' },
  { category: 'Cloud Azure', name: 'Microsoft Learn — Azure free paths', type: 'Free learning paths', url: 'https://learn.microsoft.com/en-us/training/azure/' },
  { category: 'Cloud Azure', name: 'Azure Functions Docs', type: 'Free docs', url: 'https://learn.microsoft.com/en-us/azure/azure-functions/' },
  { category: 'Cloud Azure', name: 'John Savill AZ-305 YouTube', type: 'Free AZ-305 prep', url: 'https://www.youtube.com/@NTFAQGuy' },
  { category: 'Cloud Azure', name: 'Azure Cosmos DB free tier', type: 'Free DB tier', url: 'https://learn.microsoft.com/en-us/azure/cosmos-db/free-tier' },
  { category: 'Cloud AWS', name: 'Andrew Brown freeCodeCamp SAA-C03', type: 'Free 14hr SAA course', url: 'https://www.youtube.com/watch?v=Ia-UEYYR44s' },
  { category: 'Cloud AWS', name: 'AWS Free Tier', type: '12 months free', url: 'https://aws.amazon.com/free/' },
  { category: 'Deployment', name: 'Vercel — Next.js hosting free', type: 'Free tier', url: 'https://vercel.com/' },
  { category: 'Deployment', name: 'Railway — DB + backend hosting', type: 'Free tier', url: 'https://railway.app/' },
  { category: 'Deployment', name: 'Render — NestJS hosting', type: 'Free tier', url: 'https://render.com/' },
  { category: 'TypeScript', name: 'TypeScript Deep Dive free ebook', type: 'Free ebook', url: 'https://basarat.gitbook.io/typescript/' },
  { category: 'TypeScript', name: 'Matt Pocock TS YouTube', type: 'Free YouTube', url: 'https://www.youtube.com/c/MattPocockUk' },
  { category: 'SQL', name: 'Mode SQL Tutorial', type: 'Free SQL tutorial', url: 'https://mode.com/sql-tutorial/' },
  { category: 'SQL', name: 'SQLZoo', type: 'Free interactive SQL', url: 'https://sqlzoo.net/' },
  { category: 'JS Practice', name: 'JavaScript30 by Wes Bos', type: 'Free 30-day challenge', url: 'https://javascript30.com/' },
  { category: 'Machine Coding', name: 'GreatFrontEnd problems', type: 'Free + paid practice', url: 'https://www.greatfrontend.com/' },
  { category: 'Job Portals', name: 'Instahyre', type: 'Hidden from employer', url: 'https://www.instahyre.com/' },
  { category: 'Job Portals', name: 'Hirist.tech', type: 'Tech-only portal', url: 'https://hirist.tech/' },
  { category: 'Job Portals', name: 'Cutshort', type: 'Skill-verified roles', url: 'https://cutshort.io/' },
  { category: 'Job Portals', name: 'Wellfound AngelList', type: 'Startup + ESOP jobs', url: 'https://wellfound.com/jobs' },
  { category: 'Job Portals', name: 'Peerlist', type: 'Dev community + jobs', url: 'https://peerlist.io/' },
  { category: 'Job Portals', name: 'Grapevine India', type: 'Salary intel + referrals', url: 'https://www.grapevine.in/' },
  { category: 'Job Portals', name: 'r/developersIndia Discord', type: 'Community referrals', url: 'https://discord.com/invite/developersindia-669880381649977354' },
  { category: 'Salary Data', name: 'Levels.fyi India', type: 'Salary benchmarks', url: 'https://www.levels.fyi/t/software-engineer/location/India' },
  { category: 'Salary Data', name: 'AmbitionBox salaries', type: 'India salary data', url: 'https://www.ambitionbox.com/salaries/' },
  { category: 'Salary Data', name: 'Glassdoor India', type: 'Salary + interviews', url: 'https://www.glassdoor.co.in/' },
  { category: 'Negotiation', name: 'Haseeb Qureshi — 10 negotiation rules', type: 'Free article', url: 'https://haseebq.com/my-ten-rules-for-negotiating-a-job-offer/' },
  { category: 'Behavioral', name: 'Amazon Leadership Principles', type: 'Free reference', url: 'https://www.amazon.jobs/content/en/our-workplace/leadership-principles' },
  { category: 'Tools', name: 'Carbon.now.sh — code screenshots', type: 'Free tool', url: 'https://carbon.now.sh/' },
  { category: 'Tools', name: 'Shields.io — README badges', type: 'Free tool', url: 'https://shields.io/' },
  { category: 'Tools', name: 'github-readme-stats', type: 'Free GitHub widget', url: 'https://github.com/anuraghazra/github-readme-stats' },
  { category: 'Tools', name: 'Loom — video self-practice', type: 'Free tier', url: 'https://www.loom.com/' },
  { category: 'Content', name: 'Hashnode — technical blogging', type: 'Free blog platform', url: 'https://hashnode.com/' },
  { category: 'Content', name: 'dev.to — developer community', type: 'Free blog + community', url: 'https://dev.to/' },
  { category: 'OSS', name: 'NestJS good first issues', type: 'OSS contributions', url: 'https://github.com/nestjs/nest/issues?q=label%3A%22good+first+issue%22' },
  { category: 'OSS', name: 'Single-SPA issues', type: 'OSS contributions', url: 'https://github.com/single-spa/single-spa/issues' },
  { category: 'OSS', name: 'Next.js good first issues', type: 'OSS contributions', url: 'https://github.com/vercel/next.js/issues?q=label%3A%22good+first+issue%22' },
]

// ── Seeder function ───────────────────────────────────────────────────────────
export async function seedDatabase(): Promise<void> {
  const seedVersion = localStorage.getItem('jobradar-seed-version')
  if (seedVersion === '1') return

  await db.transaction(
    'rw',
    [db.weekTargets, db.dsaProblems, db.resources, db.skills, db.tactics, db.prepEntries],
    async () => {
      await db.weekTargets.bulkAdd(WEEK_TARGETS_SEED as WeekTarget[])
      await db.dsaProblems.bulkAdd(DSA_PROBLEMS_SEED as DSAProblem[])
      await db.resources.bulkAdd(RESOURCES_SEED as Resource[])
      await db.skills.bulkAdd(SKILLS_SEED as Skill[])
      await db.tactics.bulkAdd(TACTICS_SEED as Tactic[])
      await db.prepEntries.bulkAdd(PREP_SEED as PrepEntry[])
    }
  )

  localStorage.setItem('jobradar-seed-version', '1')
}